### ISSUE TITLE
Adding type exports to packages/gamut/index.tsx breaks storybook

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/client-modules#352]
Errors like this come up:

> `export 'CardBodyProps' was not found in './Card/CardBody`

```
 | ERR! /home/circleci/repo/packages/gamut/index.tsx 5:0-69
 | ERR! "export 'CardBodyProps' was not found in './Card/CardBody'
 | ERR!     at HarmonyExportImportedSpecifierDependency._getErrors (/home/circleci/repo/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:383:11)
 | ERR!     at HarmonyExportImportedSpecifierDependency.getErrors (/home/circleci/repo/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:338:16)
 | ERR!     at Compilation.reportDependencyErrorsAndWarnings (/home/circleci/repo/node_modules/webpack/lib/Compilation.js:1365:22)
 | ERR!     at Compilation.finish (/home/circleci/repo/node_modules/webpack/lib/Compilation.js:1167:9)
 | ERR!     at hooks.make.callAsync.err (/home/circleci/repo/node_modules/webpack/lib/Compiler.js:622:17)
 | ERR!     at _done (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
 | ERR!     at _err1 (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
 | ERR!     at _addModuleChain (/home/circleci/repo/node_modules/webpack/lib/Compilation.js:1095:12)
 | ERR!     at processModuleDependencies.err (/home/circleci/repo/node_modules/webpack/lib/Compilation.js:1007:9)
 | ERR!     at _combinedTickCallback (workspaces/gamut-storybook/internal/process/next_tick.js:131:7)
 | ERR!     at process._tickCallback (workspaces/gamut-storybook/internal/process/next_tick.js:180:9)
 | ERR!  @ workspaces/gamut-storybook/stories/Form-story.js
 | ERR!  @ ./stories sync \.*-story\.jsx?$
 | ERR!  @ workspaces/gamut-storybook/.storybook/config.js
 | ERR!  @ multi /home/circleci/repo/node_modules/@workspaces/gamut-storybook/storybook/core/dist/server/common/polyfills.js /home/circleci/repo/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js
```

Example build: https://circleci.com/gh/RyzacInc/client-modules/8886

The errors don't pop up doing regular PR builds, just when you run `yarn run build-storybook`.

**Comment by JoshuaKGoldberg** [comment]
no

**Comment by JoshuaKGoldberg** [comment]
```

ERROR in ../gamut/src/index.tsx 1:0-44
"export 'BadgeProps' was not found in './Badge'
 @ ./stories/Badge.stories.js
 @ ./stories sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.stories\.(mdx|js))$
 @ ./.storybook/generated-entry.js
 @ multi /Users/josh/repos/client-modules/node_modules/@storybook/core/dist/server/common/polyfills.js /Users/josh/repos/client-modules/node_modules/@storybook/core/dist/server/preview/globals.js /Users/josh/repos/client-modules/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js /Users/josh/repos/client-modules/node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/preview.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by JoshuaKGoldberg** [comment]
ugh

**Comment by JoshuaKGoldberg** [comment]
STOP IT GITHUB

**Comment by JoshuaKGoldberg** [comment]
Actually, I think the `export *` syntax fixed this. 🤗
